//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomWSR.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculation
    {
        public int ID { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public Nullable<int> Effiency { get; set; }
        public Nullable<decimal> TotalSum { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CreaterID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
